#
# Copyright 2017-2020 the original author or authors from the JHipster project.
#
# This file is part of the JHipster project, see https://www.jhipster.tech/
# for more information.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#

pool:
  vmImage: 'Ubuntu 16.04'

variables:
  NODE_VERSION: 10.16.3
  SPRING_OUTPUT_ANSI_ENABLED: ALWAYS
  SPRING_JPA_SHOW_SQL: false

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '10.16.3'
  displayName: 'TOOLS: install Node.js'

- bash: npm install -g yarn
  displayName: 'TOOLS: install yarn'

- script: |
    set -e
    sudo add-apt-repository ppa:openjdk-r/ppa
    sudo apt-get update
    sudo apt-get install -y openjdk-8-jdk
    sudo update-java-alternatives -s java-1.8.0-openjdk-amd64
    java -version
  displayName: 'TOOLS: configuring OpenJDK'

- bash: sudo /etc/init.d/mysql stop
  displayName: 'CONFIGURE: shutdown mysql database'

- bash: yarn install
  displayName: 'INSTALL: dependencies'

- script: |
    set -e
    chmod +x mvnw
    ./mvnw clean test
    yarn test
    ./mvnw verify -Pprod -DskipTests
  displayName: 'TEST: run test'
