apiVersion: v1
kind: Service
metadata:
  name: jhonline
  namespace: default
  labels:
    app: jhonline
spec:
  selector:
    app: jhonline
  type: LoadBalancer
  ports:
  - name: http
    port: 8080
